"""Write the static-mesh catalogue the dressing agents pick props from (run live in the editor):

  python Tools/Unreal/kg_remote.py -f Tools/Unreal/kg_asset_catalog.py --timeout 600

-> Tools/Unreal/dressing/asset_catalog.md (+ .json): every StaticMesh under /Game/KillGodot with its bounds
   (size X x Y x Z cm, and min Z: ~0 means the pivot sits on the ground).
"""
import json

import unreal

OUT = "D:/Kill Godot/Tools/Unreal/dressing/asset_catalog"
reg = unreal.AssetRegistryHelpers.get_asset_registry()
flt = unreal.ARFilter(package_paths=["/Game/KillGodot"], recursive_paths=True,
                      class_paths=[unreal.TopLevelAssetPath("/Script/Engine", "StaticMesh")])
# Stale folders from failed imports (materials broken) and non-dressing meshes: never place these.
SKIP = ("/Env/Pirate/", "/Env/PirateC2/", "/Env/PirateClean/", "/Env/PirateProps/", "/Env/Japan/", "/Env/JapanProps/",
        "/Cosmetics/", "/Env/Grass/", "/Env/Terrain/", "/Env/Sea/")
rows = []
for ad in reg.get_assets(flt):
    path = str(ad.package_name)
    if any(k in path for k in SKIP):
        continue
    m = unreal.load_asset(path)
    if not m:
        continue
    b = m.get_bounding_box()
    mn, mx = b.min, b.max
    if any(v != v for v in (mn.x, mn.y, mn.z, mx.x, mx.y, mx.z)):   # NaN bounds: broken/empty mesh
        continue
    rows.append({"path": path, "folder": path.rsplit("/", 1)[0], "name": path.rsplit("/", 1)[1],
                 "size": [round(mx.x - mn.x), round(mx.y - mn.y), round(mx.z - mn.z)],
                 "min": [round(mn.x), round(mn.y), round(mn.z)]})
rows.sort(key=lambda r: r["path"])
json.dump(rows, open(OUT + ".json", "w"), indent=1)
lines = ["# Static mesh catalogue (/Game/KillGodot)", "",
         "Generated by Tools/Unreal/kg_asset_catalog.py. size = X x Y x Z cm; minZ ~0 => pivot on the ground,",
         "min X/Y ~ -size/2 => pivot centred. Paths are package paths (use them directly with kg_dress_common.place).", ""]
folder = None
for r in rows:
    if r["folder"] != folder:
        folder = r["folder"]
        lines += ["", f"## {folder}/", ""]
    sx, sy, sz = r["size"]
    lines.append(f"- {r['name']}  {sx}x{sy}x{sz}  min({r['min'][0]},{r['min'][1]},{r['min'][2]})")
open(OUT + ".md", "w").write("\n".join(lines) + "\n")
print(f"KG_CATALOG {len(rows)} meshes -> {OUT}.md")
