#pragma once

#include "CoreMinimal.h"

struct FSlateBrush;

/**
 * The game's own emoji set (Slate cannot draw colour emoji fonts). 32 sticker-style images generated by
 * Tools/UI/kg_make_emoji.py into two atlases (8 x 4 cells):
 *   /Game/KillGodot/UI/Emoji/T_KG_EmojiAtlas        160 px cells  (reaction bubbles, picker, wheel)
 *   /Game/KillGodot/UI/Emoji/T_KG_EmojiAtlas_Small  48 px cells   (inline in chat lines and the input box)
 *
 * In strings an emoji is ONE private-use character (U+E100 + index), so length caps count it as one character,
 * editable text treats it as one glyph, and the wire format stays a plain FString. Typing :skull:, :) or <3 (or
 * pasting a real Unicode emoji) is converted to that character; FKGEmoji::ToPlainText turns it back into :id: for
 * logs and plain STextBlocks.
 */
class KILLGODOT_API FKGEmoji
{
public:
	static constexpr TCHAR FirstChar = 0xE100;

	static int32 Num();
	/** Canonical id ("skull"); nullptr when out of range. */
	static const TCHAR* GetId(int32 Index);
	/** Id or alias ("rip", "+1", "lol"), case-insensitive, without colons. INDEX_NONE if unknown. */
	static int32 Find(const FString& NameOrAlias);
	static TCHAR ToChar(int32 Index) { return static_cast<TCHAR>(FirstChar + Index); }
	/** Emoji index of a private-use character, INDEX_NONE for anything else. */
	static int32 FromChar(TCHAR Char);
	static bool IsEmojiChar(TCHAR Char) { return FromChar(Char) != INDEX_NONE; }
	static int32 CountEmojis(const FString& Text);

	/** ":skull:" -> emoji char. Unknown codes are left as typed. */
	static FString ConvertShortcodes(const FString& Text);
	/** ":)" ":D" "<3" ":(" ";)" ":o" ">:(" ":/" "o/" "xD" as whole words -> emoji char. */
	static FString ConvertEmoticons(const FString& Text);
	/** Real Unicode emoji (surrogate pairs and BMP symbols) -> our set; variation selectors / ZWJ dropped. */
	static FString ConvertUnicode(const FString& Text);
	/** All three conversions. */
	static FString ConvertAll(const FString& Text);
	/** Emoji chars -> ":id:" (logs, plain text widgets). */
	static FString ToPlainText(const FString& Text);

	/** Brush from the small atlas at Size x Size slate units (inline text). Null until the atlas is loaded. */
	static const FSlateBrush* GetInlineBrush(int32 Index, int32 Size = 20);
	/** Brush from the large atlas (picker, bubbles, wheel); ImageSize = Size. Null if the atlas is missing. */
	static const FSlateBrush* GetLargeBrush(int32 Index, int32 Size = 36);
};
