#pragma once

#include "CoreMinimal.h"
#include "Containers/Ticker.h"
#include "UObject/WeakObjectPtr.h"
#include "UObject/WeakObjectPtrTemplates.h"

class AGameModeBase;
class APlayerController;
class FOnlineSessionSearch;
class UGameInstance;
struct FUniqueNetIdRepl;

/** One advertised match, flattened for the lobby browser. */
struct FKGSessionRow
{
	int32 SearchIndex = INDEX_NONE;
	FString Name;
	FString HostName;
	FString MapPath;
	FString MapTitle;
	int32 Players = 0;
	int32 MaxPlayers = 0;
	/** Round-trip in ms, -1 when the backend does not measure it. */
	int32 PingMs = -1;
	bool bInProgress = false;
	bool bPassword = false;
	/** Six-character join code ("" for old hosts). */
	FString Code;
	/** Coarse region tag of the host ("EU", "NA", ...). */
	FString Region;

	bool IsFull() const { return MaxPlayers > 0 && Players >= MaxPlayers; }
};

/** What the Host screen asks for. */
struct FKGHostOptions
{
	FString Name;
	FString MapPath;
	FString MapTitle;
	int32 MaxPlayers = 12;
	/** Not listed in the browser (join by IP / invite only). */
	bool bPrivate = false;
	/** Empty = open. Only a hash is kept and compared. */
	FString Password;
	/** Join code shown in the lobby; generated by Host() when empty. */
	FString Code;
	/** Region tag advertised with the match; guessed from the UTC offset when empty. */
	FString Region;
};

DECLARE_DELEGATE_TwoParams(FKGOnSessionsFound, bool /*bSuccess*/, const TArray<FKGSessionRow>& /*Rows*/);
DECLARE_DELEGATE_TwoParams(FKGOnSessionResult, bool /*bSuccess*/, const FText& /*Message*/);

/**
 * Player-hosted match advertising and discovery through the online subsystem's session interface. Subsystem
 * agnostic: with OnlineSubsystemNull it is LAN (beacons, works in PIE and between local instances); with
 * OnlineSubsystemEOS it uses EOS Lobbies and the NetDriverEOS P2P relay (Docs/Online_EOS_Setup.md).
 *
 *   Host:  OpenLevel(map ?listen) first, then CreateSession once the listen net driver is up (the advertised
 *          address/port comes from it), then keep player count / in-progress up to date with UpdateSession.
 *   Find:  FindSessions -> rows (only Kill Godot sessions: they carry the KG_NAME attribute).
 *   Join:  JoinSession -> GetResolvedConnectString -> ClientTravel (+ password hash as a URL option).
 *   Leave: DestroySession (leave to menu, quit, disconnect, arriving at the front end).
 *
 * Plain C++ with per-GameInstance state, so several PIE players in one process each have their own session.
 */
class KILLGODOT_API FKGSessions
{
public:
	static FKGSessions& Get();

	/** "LAN", "Epic Online Services" or the raw subsystem name; "Offline" when there is no session interface. */
	FText GetBackendName(const UObject* WorldContext) const;

	/** Display name of the local player (online nickname, else the OS user name). */
	FString GetLocalPlayerName(const APlayerController* PC) const;

	/** Travels to Options.MapPath as a listen server and advertises it once the server is up. */
	void Host(APlayerController* PC, const FKGHostOptions& Options, FKGOnSessionResult OnDone = FKGOnSessionResult());

	/** Searches for open Kill Godot matches. */
	void Find(APlayerController* PC, FKGOnSessionsFound OnDone);

	/** Joins row SearchIndex of the last Find() and travels there. */
	void Join(APlayerController* PC, int32 SearchIndex, const FString& Password, FKGOnSessionResult OnDone);

	/** Stops a running Find(); its callback is not called. */
	void CancelFind(const UObject* WorldContext);

	/** Quick match choice: open (no password, not full), lobby before in-progress, livelier, lower ping. INDEX_NONE = host. */
	static int32 PickQuickMatch(const TArray<FKGSessionRow>& Rows);

	/** Destroys the session of this game instance (host or client). Safe to call when there is none. */
	void EndSession(const UObject* WorldContext);

	bool IsSearching(const UObject* WorldContext) const;

	/** One line for the pause menu about the hosted match ("Listed as ..." / "Private" / "Not advertised"). */
	FText DescribeHostedSession(const UObject* WorldContext) const;

	static FString HashPassword(const FString& Password);

	/** Options of the match this game instance hosts (pending or advertised), nullptr when not hosting. */
	const FKGHostOptions* GetHostOptions(const UObject* WorldContext) const;

	/** Host changed the lobby size / map: re-advertise. */
	void UpdateHostedMaxPlayers(const UObject* WorldContext, int32 MaxPlayers);
	void UpdateHostedMap(const UObject* WorldContext, const FString& MapPath, const FString& MapTitle);

	/** Random six-character code from an unambiguous alphabet (no 0/O, 1/I). */
	static FString MakeJoinCode();

	/** Whether typed text is a join code rather than an address. */
	static bool LooksLikeJoinCode(const FString& Text);
	static FString NormalizeJoinCode(const FString& Text);

	/** Region tags offered by the browser filter, in display order. */
	static const TArray<FString>& GetRegions();
	static FString GuessLocalRegion();

	/** URL option the client sends with the password hash; checked by the host before login. */
	static const TCHAR* PasswordOption() { return TEXT("KGPass"); }

private:
	struct FContext;

	FKGSessions();
	TSharedRef<FContext> ContextFor(const UObject* WorldContext);
	TSharedPtr<FContext> FindContext(const UObject* WorldContext) const;
	bool Tick(float DeltaTime);
	void TickHost(UGameInstance* GameInstance, FContext& Context);
	void CreateHostedSession(UGameInstance* GameInstance, const TSharedRef<FContext>& Context);
	void HandlePreLogin(AGameModeBase* GameMode, const FUniqueNetIdRepl& NewPlayer, FString& ErrorMessage);

	TMap<TWeakObjectPtr<UGameInstance>, TSharedRef<FContext>> Contexts;
	FTSTicker::FDelegateHandle TickHandle;
	float TickAccumulator = 0.0f;
};
